# Configuration Settings for C94-M8P device
ardusimple/f9p_ublox:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyARDS
    frame_id: gps
    uart1:
      baudrate: 115200
    config_on_startup: false
    rate: 1.0
    nav_rate: 1
    publish:
      all: true